#!/usr/bin/env bash
set -euo pipefail

ROOT="/workspaces/advocate-mahbub-website"
cd "$ROOT"

TARGET="src/scripts/hissa-calculator.js"
STAMP="$(date +%Y-%m-%d-%H%M%S)"
BACKUP_DIR="backups/hissa-sprint-3ab-$STAMP"

mkdir -p "$BACKUP_DIR"
cp "$TARGET" "$BACKUP_DIR/hissa-calculator.js"

echo "Backup created: $BACKUP_DIR"

export HissaRendererPayload="ZnVuY3Rpb24gcmVuZGVyUmVzdWx0KHJlc3VsdCkgewogIGNvbnN0IHVuaXQgPSBnZXRDdXJyZW50U3RhdGUoKS5sYW5kVW5pdCB8fCAi4Ka24Kak4KaVIjsKCiAgZWxlbWVudHMucmVzdWx0Um93cy5pbm5lckhUTUwgPSByZXN1bHQucm93cwogICAgLm1hcCgocm93LCBpbmRleCkgPT4gewogICAgICBjb25zdCBzb3VyY2VSb3cgPSBnZXRDdXJyZW50U3RhdGUoKS5yb3dzW2luZGV4XSB8fCB7fTsKICAgICAgY29uc3QgaGlzc2EgPSBmb3JtYXRJbnB1dEhpc3NhKHNvdXJjZVJvdyk7CgogICAgICByZXR1cm4gYAogICAgICAgIDxhcnRpY2xlIGNsYXNzPSJoaXNzYS1yZXN1bHQtcm93Ij4KICAgICAgICAgIDxkaXYgY2xhc3M9Imhpc3NhLXJlc3VsdC1wZXJzb24iPgogICAgICAgICAgICA8c3BhbiBjbGFzcz0iaGlzc2EtcmVzdWx0LWluZGV4Ij4ke2JhbmdsYU51bWJlcihpbmRleCArIDEpfTwvc3Bhbj4KICAgICAgICAgICAgPHN0cm9uZz4ke2VzY2FwZUh0bWwoCiAgICAgICAgICAgICAgcm93Lm5hbWUgfHwgc291cmNlUm93Lm5hbWUgfHwgYOCmtuCmsOCmv+CmlSAke2JhbmdsYU51bWJlcihpbmRleCArIDEpfWAKICAgICAgICAgICAgKX08L3N0cm9uZz4KICAgICAgICAgIDwvZGl2PgoKICAgICAgICAgIDxkaXYgY2xhc3M9Imhpc3NhLXJlc3VsdC1sYW5kIj4KICAgICAgICAgICAgPHN0cm9uZz4ke2Zvcm1hdExhbmQocm93LmFsbG9jYXRlZExhbmQpfTwvc3Ryb25nPgogICAgICAgICAgICA8c3Bhbj4ke2VzY2FwZUh0bWwodW5pdCl9PC9zcGFuPgogICAgICAgICAgPC9kaXY+CgogICAgICAgICAgPGRpdiBjbGFzcz0iaGlzc2EtcmVzdWx0LW1ldGEiPgogICAgICAgICAgICA8c3Bhbj4KICAgICAgICAgICAgICDgprngpr/gprjgp43gpq/gpr7gprAg4KaF4KaC4Ka2OgogICAgICAgICAgICAgIDxzdHJvbmc+JHtlc2NhcGVIdG1sKGhpc3NhLnN5bWJvbCl9PC9zdHJvbmc+CiAgICAgICAgICAgIDwvc3Bhbj4KCiAgICAgICAgICAgIDxzbWFsbD4oJHtlc2NhcGVIdG1sKGhpc3NhLnRleHQpfSk8L3NtYWxsPgoKICAgICAgICAgICAgPHNwYW4+CiAgICAgICAgICAgICAg4Kam4Ka24Kau4Ka/4KaV4KeHIOCmheCmguCmtjoKICAgICAgICAgICAgICAke2Zvcm1hdFBlcmNlbnQocm93LmFic29sdXRlUmF0aW8pfQogICAgICAgICAgICA8L3NwYW4+CiAgICAgICAgICA8L2Rpdj4KICAgICAgICA8L2FydGljbGU+CiAgICAgIGA7CiAgICB9KQogICAgLmpvaW4oIiIpOwoKICBlbGVtZW50cy5yZXN1bHQuaGlkZGVuID0gZmFsc2U7CgogIGlmIChlbGVtZW50cy50cmFjZUxpc3QpIHsKICAgIGVsZW1lbnRzLnRyYWNlTGlzdC5pbm5lckhUTUwgPSBidWlsZEJhbmdsYVRyYWNlKHJlc3VsdCk7CiAgfQp9CgpmdW5jdGlvbiBub3JtYWxpemVJbnRlZ2VySW5wdXQodmFsdWUpIHsKICBjb25zdCByYXcgPSBTdHJpbmcodmFsdWUgPz8gIiIpLnRyaW0oKTsKICBpZiAoIXJhdykgcmV0dXJuIG51bGw7CgogIGNvbnN0IG5vcm1hbGl6ZWQgPSByYXcKICAgIC5yZXBsYWNlKC9b4KemLeCnr10vZywgKGQpID0+ICLgp6bgp6fgp6jgp6ngp6rgp6vgp6zgp63gp67gp68iLmluZGV4T2YoZCkpCiAgICAucmVwbGFjZSgvW9msLF0vZywgIiIpOwoKICBpZiAoIS9eXGQrJC8udGVzdChub3JtYWxpemVkKSkgcmV0dXJuIG51bGw7CiAgcmV0dXJuIE51bWJlcihub3JtYWxpemVkKTsKfQoKY29uc3QgSGlzc2FMaW1pdHMgPSBPYmplY3QuZnJlZXplKHsKICBhbm5hOiB7IG1pbjogMCwgbWF4OiAxNSwgbGFiZWw6ICLgpobgpqjgpr4iIH0sCiAgZ29uZGE6IHsgbWluOiAwLCBtYXg6IDE5LCBsYWJlbDogIuCml+CmqOCnjeCmoeCmviIgfSwKICBrb3JhOiB7IG1pbjogMCwgbWF4OiAzLCBsYWJlbDogIuCmleCmoeCmvOCmviIgfSwKICBrcmFudGk6IHsgbWluOiAwLCBtYXg6IDIsIGxhYmVsOiAi4KaV4KeN4Kaw4Ka+4Kao4KeN4Kak4Ka/IiB9LAogIHRpbDogeyBtaW46IDAsIG1heDogMTksIGxhYmVsOiAi4Kak4Ka/4KayIiB9LAp9KTsKCmZ1bmN0aW9uIHZhbGlkYXRlSGlzc2FGaWVsZCh2YWx1ZSwga2V5KSB7CiAgY29uc3QgbGltaXQgPSBIaXNzYUxpbWl0c1trZXldOwogIGlmICghbGltaXQpIHJldHVybiBudWxsOwoKICBjb25zdCByYXcgPSBTdHJpbmcodmFsdWUgPz8gIiIpLnRyaW0oKTsKICBpZiAoIXJhdykgcmV0dXJuIDA7CgogIGNvbnN0IG51bWJlciA9IG5vcm1hbGl6ZUludGVnZXJJbnB1dChyYXcpOwoKICBpZiAobnVtYmVyID09PSBudWxsKSB7CiAgICB0aHJvdyBuZXcgRXJyb3IoYCR7bGltaXQubGFiZWx9LeCmjyDgprbgp4Hgpqfgp4Eg4Kem4oCT4KevIOCmquCmsOCnjeCmr+CmqOCnjeCmpCDgprjgpoLgppbgp43gpq/gpr4g4Kas4KeN4Kav4Kas4Ka54Ka+4KawIOCmleCmsOCngeCmqOClpGApOwogIH0KCiAgaWYgKG51bWJlciA8IGxpbWl0Lm1pbiB8fCBudW1iZXIgPiBsaW1pdC5tYXgpIHsKICAgIHRocm93IG5ldyBFcnJvcigKICAgICAgYCR7bGltaXQubGFiZWx9LeCmj+CmsCDgpq7gpr7gpqggJHtsaW1pdC5taW59IOCmpeCnh+CmleCnhyAke2xpbWl0Lm1heH0t4KaP4KawIOCmruCmp+CnjeCmr+CnhyDgprngpqTgp4cg4Ka54Kas4KeH4KWkYAogICAgKTsKICB9CgogIHJldHVybiBudW1iZXI7Cn0KCmZ1bmN0aW9uIHZhbGlkYXRlQ3VycmVudFJvd3Mocm93cykgewogIHJldHVybiByb3dzLm1hcCgocm93LCBpbmRleCkgPT4gKHsKICAgIC4uLnJvdywKICAgIG5hbWU6IFN0cmluZyhyb3cubmFtZSA/PyAiIikudHJpbSgpLAogICAgYW5uYTogdmFsaWRhdGVIaXNzYUZpZWxkKHJvdy5hbm5hLCAiYW5uYSIpLAogICAgZ29uZGE6IHZhbGlkYXRlSGlzc2FGaWVsZChyb3cuZ29uZGEsICJnb25kYSIpLAogICAga29yYTogdmFsaWRhdGVIaXNzYUZpZWxkKHJvdy5rb3JhLCAia29yYSIpLAogICAga3JhbnRpOiB2YWxpZGF0ZUhpc3NhRmllbGQocm93LmtyYW50aSwgImtyYW50aSIpLAogICAgdGlsOiB2YWxpZGF0ZUhpc3NhRmllbGQocm93LnRpbCwgInRpbCIpLAogICAgX19pbmRleDogaW5kZXgsCiAgfSkpOwp9Cgpjb25zdCBBTk5BX1NZTUJPTFMgPSBPYmplY3QuZnJlZXplKHsKICAwOiAiIiwKICAxOiAi4oGEIiwKICAyOiAi4Ke1IiwKICAzOiAi4Ke2IiwKICA0OiAi4Ke3IiwKICA1OiAi4Ke34oGEIiwKICA2OiAi4Ke34Ke1IiwKICA3OiAi4Ke34Ke2IiwKICA4OiAi4Ke34Ke3IiwKICA5OiAi4Ke34Ke34oGEIiwKICAxMDogIuCnt+Cnt+CntSIsCiAgMTE6ICLgp7fgp7fgp7YiLAogIDEyOiAi4Ke4IiwKICAxMzogIuCnuOKBhCIsCiAgMTQ6ICLgp7jgp7UiLAogIDE1OiAi4Ke44Ke2IiwKICAxNjogIuCnpyIsCn0pOwoKY29uc3QgS09SQV9TWU1CT0xTID0gT2JqZWN0LmZyZWV6ZSh7CiAgMDogIiIsCiAgMTogIuCntyIsCiAgMjogIuCnt+CntyIsCiAgMzogIuCnuCIsCn0pOwoKY29uc3QgS1JBTlRJX1NZTUJPTFMgPSBPYmplY3QuZnJlZXplKHsKICAwOiAiIiwKICAxOiAi4Ke0IiwKICAyOiAi4Ke04Ke0IiwKfSk7CgpmdW5jdGlvbiBmb3JtYXRJbnB1dEhpc3NhKHJvdykgewogIGNvbnN0IGFubmEgPSBub3JtYWxpemVJbnRlZ2VySW5wdXQocm93LmFubmEpID8/IDA7CiAgY29uc3QgZ29uZGEgPSBub3JtYWxpemVJbnRlZ2VySW5wdXQocm93LmdvbmRhKSA/PyAwOwogIGNvbnN0IGtvcmEgPSBub3JtYWxpemVJbnRlZ2VySW5wdXQocm93LmtvcmEpID8/IDA7CiAgY29uc3Qga3JhbnRpID0gbm9ybWFsaXplSW50ZWdlcklucHV0KHJvdy5rcmFudGkpID8/IDA7CiAgY29uc3QgdGlsID0gbm9ybWFsaXplSW50ZWdlcklucHV0KHJvdy50aWwpID8/IDA7CgogIGNvbnN0IHN5bWJvbCA9CiAgICBgJHtBTk5BX1NZTUJPTFNbYW5uYV0gPz8gIiJ9YCArCiAgICBgJHtnb25kYSA/IGJhbmdsYU51bWJlcihnb25kYSkgOiAiIn1gICsKICAgIGAke0tPUkFfU1lNQk9MU1trb3JhXSA/PyAiIn1gICsKICAgIGAke0tSQU5USV9TWU1CT0xTW2tyYW50aV0gPz8gIiJ9YCArCiAgICBgJHt0aWwgPyBiYW5nbGFOdW1iZXIodGlsKSA6ICIifWA7CgogIHJldHVybiB7CiAgICBzeW1ib2w6IHN5bWJvbCB8fCAi4KemIiwKICAgIHRleHQ6CiAgICAgIGAke2JhbmdsYU51bWJlcihhbm5hKX0g4KaG4Kao4Ka+IGAgKwogICAgICBgJHtiYW5nbGFOdW1iZXIoZ29uZGEpfSDgppfgpqjgp43gpqHgpr4gYCArCiAgICAgIGAke2JhbmdsYU51bWJlcihrb3JhKX0g4KaV4Kah4Ka84Ka+IGAgKwogICAgICBgJHtiYW5nbGFOdW1iZXIoa3JhbnRpKX0g4KaV4KeN4Kaw4Ka+4Kao4KeN4Kak4Ka/IGAgKwogICAgICBgJHtiYW5nbGFOdW1iZXIodGlsKX0g4Kak4Ka/4KayYCwKICB9Owp9CgpmdW5jdGlvbiBidWlsZEJhbmdsYVRyYWNlKHJlc3VsdCkgewogIGNvbnN0IHJvd3MgPSByZXN1bHQucm93cyB8fCBbXTsKICBjb25zdCBzdGF0ZU5vdyA9IGdldEN1cnJlbnRTdGF0ZSgpOwogIGNvbnN0IHVuaXQgPSBzdGF0ZU5vdy5sYW5kVW5pdCB8fCAi4Ka24Kak4KaVIjsKCiAgY29uc3QgaXRlbXMgPSBbCiAgICAi4Kaq4KeN4Kaw4Kak4Ka/4Kaf4Ka/IOCmtuCmsOCmv+CmleCnh+CmsCDgprngpr/gprjgp43gpq/gpr7gpoLgprYg4Kak4Ka/4Kay4KeHIOCmleCmqOCmreCmvuCmsOCnjeCmnyDgppXgprDgp4cg4Ka54Ka/4Ka44Ka+4KasIOCmleCmsOCmviDgprngpq/gprzgp4fgppvgp4fgpaQiLAogICAgYOCmruCni+CmnyDgprbgp4fgpq/gprzgpr7gprA6ICR7Zm9ybWF0VHJhY2VOdW1iZXIocmVzdWx0LnRvdGFsTGlzdGVkU2hhcmUgPz8gMCl9IOCmpOCmv+Cmsi3gpq3gpr/gpqTgp43gpqTgpr/gppUg4KaP4KaV4KaV4KWkYCwKICAgIGDgpq7gp4vgpp8gJHtmb3JtYXRMYW5kKHJlc3VsdC50b3RhbExhbmQgPz8gc3RhdGVOb3cudG90YWxMYW5kKX0gJHt1bml0fSDgppzgpq7gpr8g4Ka24Kaw4Ka/4KaV4Kam4KeH4KawIOCmueCmv+CmuOCnjeCmr+CmvuCmsCDgpoXgpqjgp4Hgpqrgpr7gpqTgp4cg4Kas4Kaj4KeN4Kaf4KaoIOCmleCmsOCmviDgprngpq/gprzgp4fgppvgp4fgpaRgLAogIF07CgogIHJvd3MuZm9yRWFjaCgocm93LCBpbmRleCkgPT4gewogICAgaXRlbXMucHVzaCgKICAgICAgYCR7YmFuZ2xhTnVtYmVyKGluZGV4ICsgMSl9IOCmqOCmruCnjeCmrOCmsCDgprbgprDgpr/gppXgp4fgprAg4Ka54Ka/4Ka44KeN4Kav4Ka+IOCmheCmqOCngeCmr+CmvuCmr+CmvOCngCBgICsKICAgICAgYCR7Zm9ybWF0TGFuZChyb3cuYWxsb2NhdGVkTGFuZCl9ICR7dW5pdH0g4Kao4Ka/4Kaw4KeN4Kan4Ka+4Kaw4KajIOCmleCmsOCmviDgprngpq/gprzgp4fgppvgp4fgpaRgCiAgICApOwogIH0pOwoKICByZXR1cm4gaXRlbXMubWFwKChpdGVtKSA9PiBgPGxpPiR7ZXNjYXBlSHRtbChpdGVtKX08L2xpPmApLmpvaW4oIiIpOwp9CgpmdW5jdGlvbiBmb3JtYXRUcmFjZU51bWJlcih2YWx1ZSkgewogIGNvbnN0IG4gPSBOdW1iZXIodmFsdWUpOwogIGlmICghTnVtYmVyLmlzRmluaXRlKG4pKSByZXR1cm4gIuCnpiI7CiAgcmV0dXJuIGJhbmdsYU51bWJlcihuLnRvTG9jYWxlU3RyaW5nKCJlbi1VUyIpKTsKfQo="

python3 - <<'PY'
from pathlib import Path
import base64
import os
import re

p = Path("src/scripts/hissa-calculator.js")
s = p.read_text(encoding="utf-8")

required = [
    'from "../domain/hissa/index.js"',
    '".hissa-mode-button"',
    '"#hissa-total-land"',
    '"#hissa-rows"',
    '"#hissa-result-rows"',
]
for token in required:
    if token not in s:
        raise SystemExit(f"ABORT: expected Hissa UI marker not found: {token}")

start = s.find("function renderResult(result) {")
if start < 0:
    raise SystemExit("ABORT: renderResult() was not found.")

m = re.search(r'\nfunction\s+[A-Za-z0-9_]+\s*\(', s[start + 10:])
if not m:
    raise SystemExit("ABORT: could not find the end of renderResult().")

end = start + 10 + m.start()
renderer = base64.b64decode(os.environ["HissaRendererPayload"]).decode("utf-8")
s = s[:start] + renderer + s[end:]

pattern = re.compile(
    r'const result\s*=\s*\n\s*state\.activeMode === "normal"\s*\n'
    r'\s*\?\s*calculateNormal\(payload\)\s*\n'
    r'\s*:\s*calculateGroupLine\(payload\);'
)

replacement = """const validatedRows = validateCurrentRows(payload.rows);

    const validatedPayload = {
      ...payload,
      rows: validatedRows,
    };

    const result =
      state.activeMode === "normal"
        ? calculateNormal(validatedPayload)
        : calculateGroupLine(validatedPayload);"""

if not pattern.search(s):
    raise SystemExit("ABORT: calculation selection block not found.")

s = pattern.sub(replacement, s, count=1)

p.write_text(s, encoding="utf-8")
print("Updated:", p)
PY

echo
echo "Running Hissa tests..."
node --test tests/hissa/*.test.js

echo
echo "Running production build..."
npm run build

echo
echo "SUCCESS"
echo "Backup: $BACKUP_DIR"
echo "Changed: $TARGET"
echo
echo "Browser QA:"
echo "  1. blank total land"
echo "  2. Anna=16"
echo "  3. Kora=7"
echo "  4. Bangla digits such as ১৫"
echo "  5. valid shareholder calculation"
